version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - gistda_test_db
        volumes:
            - D:\gistda_test:/var/www/html/
        ports:
            - 8000:80
    gistda_test_db:
        container_name: gistda_test_db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_DATABASE: gistda_test_db
            MYSQL_USER: gistda_test_db
            MYSQL_PASSWORD: 12345678
        ports:
            - "9906:3306"